language: node_js
node_js:
  - "node"
  - "8"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y pandoc


# addons:
#   code_climate:
#     repo_token:

notifications:
  email:
    on_success: change
    on_failure: change

# after_success:
#   - npm install codeclimate-test-reporter
#   - ./node_modules/.bin/tap --coverage-report=text-lcov | ./node_modules/.bin/codeclimate-test-reporter
