language: node_js
node_js:
  - "node"
  # - "8"

before_install:
  - sudo apt-get update
  - wget https://github.com/jgm/pandoc/releases/download/2.7.1/pandoc-2.7.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.7.7-1-amd64.deb


# addons:
#   code_climate:
#     repo_token:

notifications:
  email:
    on_success: change
    on_failure: change

# after_success:
#   - npm install codeclimate-test-reporter
#   - ./node_modules/.bin/tap --coverage-report=text-lcov | ./node_modules/.bin/codeclimate-test-reporter
